<?php

namespace Database\Seeders;

use App\Models\Ciudad;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CiudadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Ciudad::insert([
            ['id' => 1, 'provincia_id' => 1,  'descripcion' => 'CUENCA'],
            ['id' => 2, 'provincia_id' => 1,  'descripcion' => 'GIRÓN'],
            ['id' => 3, 'provincia_id' => 1,  'descripcion' => 'GUALACEO'],
            ['id' => 4, 'provincia_id' => 1,  'descripcion' => 'NABÓN'],
            ['id' => 5, 'provincia_id' => 1,  'descripcion' => 'PAUTE'],
            ['id' => 6, 'provincia_id' => 1,  'descripcion' => 'PUCARÁ'],
            ['id' => 7, 'provincia_id' => 1,  'descripcion' => 'SAN FERNANDO'],
            ['id' => 8, 'provincia_id' => 1,  'descripcion' => 'SANTA ISABEL'],
            ['id' => 9, 'provincia_id' => 1,  'descripcion' => 'SÍGSIG'],
            ['id' => 10, 'provincia_id' => 1, 'descripcion' => 'OÑA'],
            ['id' => 11, 'provincia_id' => 1, 'descripcion' => 'CHORDELEG'],
            ['id' => 12, 'provincia_id' => 1, 'descripcion' => 'EL PAN'],
            ['id' => 13, 'provincia_id' => 1, 'descripcion' => 'SEVILLA DE ORO'],
            ['id' => 14, 'provincia_id' => 1, 'descripcion' => 'GUACHAPALA'],
            ['id' => 15, 'provincia_id' => 1, 'descripcion' => 'CAMILO PONCE ENRÍQUEZ'],
            ['id' => 16, 'provincia_id' => 2, 'descripcion' => 'GUARANDA'],
            ['id' => 17, 'provincia_id' => 2, 'descripcion' => 'CHILLANES'],
            ['id' => 18, 'provincia_id' => 2, 'descripcion' => 'CHIMBO'],
            ['id' => 19, 'provincia_id' => 2, 'descripcion' => 'ECHEANDÍA'],
            ['id' => 20, 'provincia_id' => 2, 'descripcion' => 'SAN MIGUEL'],
            ['id' => 21, 'provincia_id' => 2, 'descripcion' => 'CALUMA'],
            ['id' => 22, 'provincia_id' => 2, 'descripcion' => 'LAS NAVES'],
            ['id' => 23, 'provincia_id' => 3, 'descripcion' => 'AZOGUES'],
            ['id' => 24, 'provincia_id' => 3, 'descripcion' => 'BIBLIÁN'],
            ['id' => 25, 'provincia_id' => 3, 'descripcion' => 'CAÑAR'],
            ['id' => 26, 'provincia_id' => 3, 'descripcion' => 'LA TRONCAL'],
            ['id' => 27, 'provincia_id' => 3, 'descripcion' => 'EL TAMBO'],
            ['id' => 28, 'provincia_id' => 3, 'descripcion' => 'DÉLEG'],
            ['id' => 29, 'provincia_id' => 3, 'descripcion' => 'SUSCAL'],
            ['id' => 30, 'provincia_id' => 4, 'descripcion' => 'TULCÁN'],
            ['id' => 31, 'provincia_id' => 4, 'descripcion' => 'BOLÍVAR'],
            ['id' => 32, 'provincia_id' => 4, 'descripcion' => 'ESPEJO'],
            ['id' => 33, 'provincia_id' => 4, 'descripcion' => 'MIRA'],
            ['id' => 34, 'provincia_id' => 4, 'descripcion' => 'MONTÚFAR'],
            ['id' => 35, 'provincia_id' => 4, 'descripcion' => 'SAN PEDRO DE HUACA'],
            ['id' => 36, 'provincia_id' => 5, 'descripcion' => 'LATACUNGA'],
            ['id' => 37, 'provincia_id' => 5, 'descripcion' => 'LA MANÁ'],
            ['id' => 38, 'provincia_id' => 5, 'descripcion' => 'PANGUA'],
            ['id' => 39, 'provincia_id' => 5, 'descripcion' => 'PUJILÍ'],
            ['id' => 40, 'provincia_id' => 5, 'descripcion' => 'SALCEDO'],
            ['id' => 41, 'provincia_id' => 5, 'descripcion' => 'SAQUISILÍ'],
            ['id' => 42, 'provincia_id' => 5, 'descripcion' => 'SIGCHOS'],
            ['id' => 43, 'provincia_id' => 6, 'descripcion' => 'RIOBAMBA'],
            ['id' => 44, 'provincia_id' => 6, 'descripcion' => 'ALAUSÍ'],
            ['id' => 45, 'provincia_id' => 6, 'descripcion' => 'COLTA'],
            ['id' => 46, 'provincia_id' => 6, 'descripcion' => 'CHAMBO'],
            ['id' => 47, 'provincia_id' => 6, 'descripcion' => 'CHUNCHI'],
            ['id' => 48, 'provincia_id' => 6, 'descripcion' => 'GUAMOTE'],
            ['id' => 49, 'provincia_id' => 6, 'descripcion' => 'GUANO'],
            ['id' => 50, 'provincia_id' => 6, 'descripcion' => 'PALLATANGA'],
            ['id' => 51, 'provincia_id' => 6, 'descripcion' => 'PENIPE'],
            ['id' => 52, 'provincia_id' => 6, 'descripcion' => 'CUMANDÁ'],
            ['id' => 53, 'provincia_id' => 7, 'descripcion' => 'MACHALA'],
            ['id' => 54, 'provincia_id' => 7, 'descripcion' => 'ARENILLAS'],
            ['id' => 55, 'provincia_id' => 7, 'descripcion' => 'ATAHUALPA'],
            ['id' => 56, 'provincia_id' => 7, 'descripcion' => 'BALSAS'],
            ['id' => 57, 'provincia_id' => 7, 'descripcion' => 'CHILLA'],
            ['id' => 58, 'provincia_id' => 7, 'descripcion' => 'EL GUABO'],
            ['id' => 59, 'provincia_id' => 7, 'descripcion' => 'HUAQUILLAS'],
            ['id' => 60, 'provincia_id' => 7, 'descripcion' => 'MARCABELÍ'],
            ['id' => 61, 'provincia_id' => 7, 'descripcion' => 'PASAJE'],
            ['id' => 62, 'provincia_id' => 7, 'descripcion' => 'PIÑAS'],
            ['id' => 63, 'provincia_id' => 7, 'descripcion' => 'PORTOVELO'],
            ['id' => 64, 'provincia_id' => 7, 'descripcion' => 'SANTA ROSA'],
            ['id' => 65, 'provincia_id' => 7, 'descripcion' => 'ZARUMA'],
            ['id' => 66, 'provincia_id' => 7, 'descripcion' => 'LAS LAJAS'],
            ['id' => 67, 'provincia_id' => 8, 'descripcion' => 'ESMERALDAS'],
            ['id' => 68, 'provincia_id' => 8, 'descripcion' => 'ELOY ALFARO'],
            ['id' => 69, 'provincia_id' => 8, 'descripcion' => 'MUISNE'],
            ['id' => 70, 'provincia_id' => 8, 'descripcion' => 'QUININDÉ'],
            ['id' => 71, 'provincia_id' => 8, 'descripcion' => 'SAN LORENZO'],
            ['id' => 72, 'provincia_id' => 8, 'descripcion' => 'ATACAMES'],
            ['id' => 73, 'provincia_id' => 8, 'descripcion' => 'RIOVERDE'],
            ['id' => 74, 'provincia_id' => 9, 'descripcion' => 'GUAYAQUIL'],
            ['id' => 75, 'provincia_id' => 9, 'descripcion' => 'ALFREDO BAQUERIZO MORENO (JUJÁN)'],
            ['id' => 76, 'provincia_id' => 9, 'descripcion' => 'BALAO'],
            ['id' => 77, 'provincia_id' => 9, 'descripcion' => 'BALZAR'],
            ['id' => 78, 'provincia_id' => 9, 'descripcion' => 'COLIMES'],
            ['id' => 79, 'provincia_id' => 9, 'descripcion' => 'DAULE'],
            ['id' => 80, 'provincia_id' => 9, 'descripcion' => 'DURÁN'],
            ['id' => 81, 'provincia_id' => 9, 'descripcion' => 'EL EMPALME'],
            ['id' => 82, 'provincia_id' => 9, 'descripcion' => 'EL TRIUNFO'],
            ['id' => 83, 'provincia_id' => 9, 'descripcion' => 'MILAGRO'],
            ['id' => 84, 'provincia_id' => 9, 'descripcion' => 'NARANJAL'],
            ['id' => 85, 'provincia_id' => 9, 'descripcion' => 'NARANJITO'],
            ['id' => 86, 'provincia_id' => 9, 'descripcion' => 'PALESTINA'],
            ['id' => 87, 'provincia_id' => 9, 'descripcion' => 'PEDRO CARBO'],
            ['id' => 88, 'provincia_id' => 9, 'descripcion' => 'SAMBORONDÓN'],
            ['id' => 89, 'provincia_id' => 9, 'descripcion' => 'SANTA LUCÍA'],
            ['id' => 90, 'provincia_id' => 9, 'descripcion' => 'SALITRE'],
            ['id' => 91, 'provincia_id' => 9, 'descripcion' => 'SAN JACINTO DE YAGUACHI'],
            ['id' => 92, 'provincia_id' => 9, 'descripcion' => 'PLAYAS'],
            ['id' => 93, 'provincia_id' => 9, 'descripcion' => 'SIMÓN BOLÍVAR'],
            ['id' => 94, 'provincia_id' => 9, 'descripcion' => 'CORONEL MARCELINO MARIDUEÑA'],
            ['id' => 95, 'provincia_id' => 9, 'descripcion' => 'LOMAS DE SARGENTILLO'],
            ['id' => 96, 'provincia_id' => 9, 'descripcion' => 'NOBOL'],
            ['id' => 97, 'provincia_id' => 9, 'descripcion' => 'GENERAL ANTONIO ELIZALDE'],
            ['id' => 98, 'provincia_id' => 9, 'descripcion' => 'ISIDRO AYORA'],
            ['id' => 99, 'provincia_id' => 10, 'descripcion' => 'IBARRA'],
            ['id' => 100, 'provincia_id' => 10, 'descripcion' => 'ANTONIO ANTE'],
            ['id' => 101, 'provincia_id' => 10, 'descripcion' => 'COTACACHI'],
            ['id' => 102, 'provincia_id' => 10, 'descripcion' => 'OTAVALO'],
            ['id' => 103, 'provincia_id' => 10, 'descripcion' => 'PIMAMPIRO'],
            ['id' => 104, 'provincia_id' => 10, 'descripcion' => 'SAN MIGUEL DE URCUQUÍ'],
            ['id' => 105, 'provincia_id' => 11, 'descripcion' => 'LOJA'],
            ['id' => 106, 'provincia_id' => 11, 'descripcion' => 'CALVAS'],
            ['id' => 107, 'provincia_id' => 11, 'descripcion' => 'CATAMAYO'],
            ['id' => 108, 'provincia_id' => 11, 'descripcion' => 'CELICA'],
            ['id' => 109, 'provincia_id' => 11, 'descripcion' => 'CHAGUARPAMBA'],
            ['id' => 110, 'provincia_id' => 11, 'descripcion' => 'ESPÍNDOLA'],
            ['id' => 111, 'provincia_id' => 11, 'descripcion' => 'GONZANAMÁ'],
            ['id' => 112, 'provincia_id' => 11, 'descripcion' => 'MACARÁ'],
            ['id' => 113, 'provincia_id' => 11, 'descripcion' => 'PALTAS'],
            ['id' => 114, 'provincia_id' => 11, 'descripcion' => 'PUYANGO'],
            ['id' => 115, 'provincia_id' => 11, 'descripcion' => 'SARAGURO'],
            ['id' => 116, 'provincia_id' => 11, 'descripcion' => 'SOZORANGA'],
            ['id' => 117, 'provincia_id' => 11, 'descripcion' => 'ZAPOTILLO'],
            ['id' => 118, 'provincia_id' => 11, 'descripcion' => 'PINDAL'],
            ['id' => 119, 'provincia_id' => 11, 'descripcion' => 'QUILANGA'],
            ['id' => 120, 'provincia_id' => 11, 'descripcion' => 'OLMEDO'],
            ['id' => 121, 'provincia_id' => 12, 'descripcion' => 'BABAHOYO'],
            ['id' => 122, 'provincia_id' => 12, 'descripcion' => 'BABA'],
            ['id' => 123, 'provincia_id' => 12, 'descripcion' => 'MONTALVO'],
            ['id' => 124, 'provincia_id' => 12, 'descripcion' => 'PUEBLOVIEJO'],
            ['id' => 125, 'provincia_id' => 12, 'descripcion' => 'QUEVEDO'],
            ['id' => 126, 'provincia_id' => 12, 'descripcion' => 'URDANETA'],
            ['id' => 127, 'provincia_id' => 12, 'descripcion' => 'VENTANAS'],
            ['id' => 128, 'provincia_id' => 12, 'descripcion' => 'VINCES'],
            ['id' => 129, 'provincia_id' => 12, 'descripcion' => 'PALENQUE'],
            ['id' => 130, 'provincia_id' => 12, 'descripcion' => 'BUENA FE'],
            ['id' => 131, 'provincia_id' => 12, 'descripcion' => 'VALENCIA'],
            ['id' => 132, 'provincia_id' => 12, 'descripcion' => 'MOCACHE'],
            ['id' => 133, 'provincia_id' => 12, 'descripcion' => 'QUINSALOMA'],
            ['id' => 134, 'provincia_id' => 13, 'descripcion' => 'PORTOVIEJO'],
            ['id' => 135, 'provincia_id' => 13, 'descripcion' => 'BOLÍVAR'],
            ['id' => 136, 'provincia_id' => 13, 'descripcion' => 'CHONE'],
            ['id' => 137, 'provincia_id' => 13, 'descripcion' => 'EL CARMEN'],
            ['id' => 138, 'provincia_id' => 13, 'descripcion' => 'FLAVIO ALFARO'],
            ['id' => 139, 'provincia_id' => 13, 'descripcion' => 'JIPIJAPA'],
            ['id' => 140, 'provincia_id' => 13, 'descripcion' => 'JUNÍN'],
            ['id' => 141, 'provincia_id' => 13, 'descripcion' => 'MANTA'],
            ['id' => 142, 'provincia_id' => 13, 'descripcion' => 'MONTECRISTI'],
            ['id' => 143, 'provincia_id' => 13, 'descripcion' => 'PAJÁN'],
            ['id' => 144, 'provincia_id' => 13, 'descripcion' => 'PICHINCHA'],
            ['id' => 145, 'provincia_id' => 13, 'descripcion' => 'ROCAFUERTE'],
            ['id' => 146, 'provincia_id' => 13, 'descripcion' => 'SANTA ANA'],
            ['id' => 147, 'provincia_id' => 13, 'descripcion' => 'SUCRE'],
            ['id' => 148, 'provincia_id' => 13, 'descripcion' => 'TOSAGUA'],
            ['id' => 149, 'provincia_id' => 13, 'descripcion' => '24 DE MAYO'],
            ['id' => 150, 'provincia_id' => 13, 'descripcion' => 'PEDERNALES'],
            ['id' => 151, 'provincia_id' => 13, 'descripcion' => 'OLMEDO'],
            ['id' => 152, 'provincia_id' => 13, 'descripcion' => 'PUERTO LÓPEZ'],
            ['id' => 153, 'provincia_id' => 13, 'descripcion' => 'JAMA'],
            ['id' => 154, 'provincia_id' => 13, 'descripcion' => 'JARAMIJÓ'],
            ['id' => 155, 'provincia_id' => 13, 'descripcion' => 'SAN VICENTE'],
            ['id' => 156, 'provincia_id' => 14, 'descripcion' => 'MORONA'],
            ['id' => 157, 'provincia_id' => 14, 'descripcion' => 'GUALAQUIZA'],
            ['id' => 158, 'provincia_id' => 14, 'descripcion' => 'LIMÓN INDANZA'],
            ['id' => 159, 'provincia_id' => 14, 'descripcion' => 'PALORA'],
            ['id' => 160, 'provincia_id' => 14, 'descripcion' => 'SANTIAGO'],
            ['id' => 161, 'provincia_id' => 14, 'descripcion' => 'SUCÚA'],
            ['id' => 162, 'provincia_id' => 14, 'descripcion' => 'HUAMBOYA'],
            ['id' => 163, 'provincia_id' => 14, 'descripcion' => 'SAN JUAN BOSCO'],
            ['id' => 164, 'provincia_id' => 14, 'descripcion' => 'TAISHA'],
            ['id' => 165, 'provincia_id' => 14, 'descripcion' => 'LOGROÑO'],
            ['id' => 166, 'provincia_id' => 14, 'descripcion' => 'PABLO SEXTO'],
            ['id' => 167, 'provincia_id' => 14, 'descripcion' => 'TIWINTZA'],
            ['id' => 168, 'provincia_id' => 15, 'descripcion' => 'TENA'],
            ['id' => 169, 'provincia_id' => 15, 'descripcion' => 'ARCHIDONA'],
            ['id' => 170, 'provincia_id' => 15, 'descripcion' => 'EL CHACO'],
            ['id' => 171, 'provincia_id' => 15, 'descripcion' => 'QUIJOS'],
            ['id' => 172, 'provincia_id' => 15, 'descripcion' => 'CARLOS JULIO AROSEMENA TOLA'],
            ['id' => 173, 'provincia_id' => 16, 'descripcion' => 'PASTAZA'],
            ['id' => 174, 'provincia_id' => 16, 'descripcion' => 'MERA'],
            ['id' => 175, 'provincia_id' => 16, 'descripcion' => 'SANTA CLARA'],
            ['id' => 176, 'provincia_id' => 16, 'descripcion' => 'ARAJUNO'],
            ['id' => 177, 'provincia_id' => 17, 'descripcion' => 'DISTRITO METROPOLITANO DE QUITO'],
            ['id' => 178, 'provincia_id' => 17, 'descripcion' => 'CAYAMBE'],
            ['id' => 179, 'provincia_id' => 17, 'descripcion' => 'MEJÍA'],
            ['id' => 180, 'provincia_id' => 17, 'descripcion' => 'PEDRO MONCAYO'],
            ['id' => 181, 'provincia_id' => 17, 'descripcion' => 'RUMIÑAHUI'],
            ['id' => 182, 'provincia_id' => 17, 'descripcion' => 'SAN MIGUEL DE LOS BANCOS'],
            ['id' => 183, 'provincia_id' => 17, 'descripcion' => 'PEDRO VICENTE MALDONADO'],
            ['id' => 184, 'provincia_id' => 17, 'descripcion' => 'PUERTO QUITO'],
            ['id' => 185, 'provincia_id' => 18, 'descripcion' => 'AMBATO'],
            ['id' => 186, 'provincia_id' => 18, 'descripcion' => 'BAÑOS DE AGUA SANTA'],
            ['id' => 187, 'provincia_id' => 18, 'descripcion' => 'CEVALLOS'],
            ['id' => 188, 'provincia_id' => 18, 'descripcion' => 'MOCHA'],
            ['id' => 189, 'provincia_id' => 18, 'descripcion' => 'PATATE'],
            ['id' => 190, 'provincia_id' => 18, 'descripcion' => 'QUERO'],
            ['id' => 191, 'provincia_id' => 18, 'descripcion' => 'SAN PEDRO DE PELILEO'],
            ['id' => 192, 'provincia_id' => 18, 'descripcion' => 'SANTIAGO DE PÍLLARO'],
            ['id' => 193, 'provincia_id' => 18, 'descripcion' => 'TISALEO'],
            ['id' => 194, 'provincia_id' => 19, 'descripcion' => 'ZAMORA'],
            ['id' => 195, 'provincia_id' => 19, 'descripcion' => 'CHINCHIPE'],
            ['id' => 196, 'provincia_id' => 19, 'descripcion' => 'NANGARITZA'],
            ['id' => 197, 'provincia_id' => 19, 'descripcion' => 'YACUAMBI'],
            ['id' => 198, 'provincia_id' => 19, 'descripcion' => 'YANTZAZA'],
            ['id' => 199, 'provincia_id' => 19, 'descripcion' => 'EL PANGUI'],
            ['id' => 200, 'provincia_id' => 19, 'descripcion' => 'CENTINELA DEL CÓNDOR'],
            ['id' => 201, 'provincia_id' => 19, 'descripcion' => 'PALANDA'],
            ['id' => 202, 'provincia_id' => 19, 'descripcion' => 'PAQUISHA'],
            ['id' => 203, 'provincia_id' => 20, 'descripcion' => 'SAN CRISTÓBAL'],
            ['id' => 204, 'provincia_id' => 20, 'descripcion' => 'ISABELA'],
            ['id' => 205, 'provincia_id' => 20, 'descripcion' => 'SANTA CRUZ'],
            ['id' => 206, 'provincia_id' => 21, 'descripcion' => 'LAGO AGRIO'],
            ['id' => 207, 'provincia_id' => 21, 'descripcion' => 'GONZALO PIZARRO'],
            ['id' => 208, 'provincia_id' => 21, 'descripcion' => 'PUTUMAYO'],
            ['id' => 209, 'provincia_id' => 21, 'descripcion' => 'SHUSHUFINDI'],
            ['id' => 210, 'provincia_id' => 21, 'descripcion' => 'SUCUMBÍOS'],
            ['id' => 211, 'provincia_id' => 21, 'descripcion' => 'CASCALES'],
            ['id' => 212, 'provincia_id' => 21, 'descripcion' => 'CUYABENO'],
            ['id' => 213, 'provincia_id' => 22, 'descripcion' => 'FRANCISCO DE ORELLANA'],
            ['id' => 214, 'provincia_id' => 22, 'descripcion' => 'AGUARICO'],
            ['id' => 215, 'provincia_id' => 22, 'descripcion' => 'LA JOYA DE LOS SACHAS'],
            ['id' => 216, 'provincia_id' => 22, 'descripcion' => 'LORETO'],
            ['id' => 217, 'provincia_id' => 23, 'descripcion' => 'SANTO DOMINGO'],
            ['id' => 218, 'provincia_id' => 23, 'descripcion' => 'LA CONCORDIA'],
            ['id' => 219, 'provincia_id' => 24, 'descripcion' => 'SANTA ELENA'],
            ['id' => 220, 'provincia_id' => 24, 'descripcion' => 'LA LIBERTAD'],
            ['id' => 221, 'provincia_id' => 24, 'descripcion' => 'SALINAS'],
        ]);
    }
}
