export const configuracionColumnasVencimientos = [
    {
        title: "Acreedor",
        field: "acreedor",
        headerSort: false,
        editor: "input",
        minWidth: 200,
    },
    {
        title: "Fecha de corte",
        field: "fecha_corte",
        headerSort: false,
        editor: "input",
        minWidth: 100,
    },
    {
        title: "Tipo riesgo",
        field: "tipo_riesgo",
        headerSort: false,
        editor: "input",
        minWidth: 100,
    },
    {
        title: "Saldo deuda",
        field: "saldo_deuda",
        headerSort: false,
        editor: "input",
        minWidth: 100,
    },
    {
        title: "Valor por vencer",
        field: "valor_por_vencer",
        headerSort: false,
        editor: "input",
        minWidth: 100,
    },
    {
        title: "No devenga Int",
        field: "no_devenga_intereses",
        headerSort: false,
        editor: "input",
        minWidth: 100,
    },
    {
        title: "Valor vencido",
        field: "valor_vencido",
        headerSort: false,
        editor: "input",
        minWidth: 100,
    },
    {
        title: "Demanda judicial",
        field: "demanda_judicial",
        headerSort: false,
        editor: "input",
        minWidth: 100,
    },
    {
        title: "Cartera castigada",
        field: "cartera_castigada",
        headerSort: false,
        editor: "input",
        minWidth: 100,
    },
    {
        title: "Tiempo vencido días",
        field: "tiempo_vencido_dias",
        headerSort: false,
        editor: "input",
        minWidth: 100,
    },
]
