export const configuracionColumnasOperacionesCredito = [
    {
        title: "Institución",
        field: "institucion",
        headerSort: false,
        editor: "input",
        minWidth: 200,
    },
    {
        title: "Fecha corte",
        field: "fecha_corte",
        headerSort: false,
        editor: "input",
        minWidth: 100,
        editorParams: { mask: "9999-99-99" },
    },
    {
        title: "Tipo riesgo",
        field: "tipo_riesgo",
        headerSort: false,
        editor: "input",
        minWidth: 100,
    },
    {
        title: "Tipo crédito",
        field: "tipo_credito",
        headerSort: false,
        editor: "input",
        minWidth: 100,
    },
    {
        title: "Cupo monto original",
        field: "cupo_monto_original",
        headerSort: false,
        editor: "input",
        minWidth: 100,
    },
    {
        title: "Fecha apertura",
        field: "fecha_apertura",
        headerSort: false,
        editor: "input",
        minWidth: 100,
        editorParams: { mask: "9999-99-99" },
    },
    {
        title: "Fecha vencimiento",
        field: "fecha_vencimiento",
        headerSort: false,
        editor: "input",
        minWidth: 100,
        editorParams: { mask: "9999-99-99" },
    },
    {
        title: "Total vencer",
        field: "total_vencer",
        headerSort: false,
        editor: "input",
        minWidth: 100,
    },
    {
        title: "NDI",
        field: "ndi",
        headerSort: false,
        editor: "input",
        minWidth: 200,
    },
    {
        title: "Total vencido",
        field: "total_vencido",
        headerSort: false,
        editor: "input",
        minWidth: 100,
    },
    {
        title: "Demanda judicial",
        field: "demanda_judicial",
        headerSort: false,
        editor: "input",
        minWidth: 200,
    },
    {
        title: "Cartera castigada",
        field: "cartera_castigada",
        headerSort: false,
        editor: "input",
        minWidth: 200,
    },
    {
        title: "Saldo deuda",
        field: "saldo_deuda",
        headerSort: false,
        editor: "input",
        minWidth: 100,
    },
    {
        title: "Cuota mensual",
        field: "cuota_mensual",
        headerSort: false,
        editor: "input",
        minWidth: 100,
    },
]
