export const configuracionColumnas = [
    {
        title: "Estado",
        field: "estado",
        sorter: "string",
        vertAlign: "middle",
        headerFilter: "input",
        width: 110,
        resizable: false,
    },
    {
        title: "Cliente",
        field: "cliente",
        sorter: "string",
        vertAlign: "middle",
        headerFilter: "input",
        width: 220,
        resizable: false,
    },
    {
        title: "Fecha de solicitud",
        field: "fecha",
        sorter: "string",
        vertAlign: "middle",
        headerFilter: "input",
        resizable: false,
    },
    {
        title: "P. Actual",
        field: "puntaje_actual",
        sorter: "string",
        vertAlign: "middle",
        headerFilter: "input",
        resizable: false,
    },
    {
        title: "P. a subir",
        field: "puntaje_subir",
        sorter: "string",
        vertAlign: "middle",
        headerFilter: "input",
        resizable: false,
    },
]
