export const configuracionColumnas = [
    {
        title: "Nombre",
        field: "name",
        sorter: "string",
        vertAlign: "middle",
        headerFilter: "input",
        resizable: false,
    },
    {
        title: "Apellidos",
        field: "apellidos",
        sorter: "string",
        vertAlign: "middle",
        headerFilter: "input",
        resizable: false,
    },
    {
        title: "Identificación",
        field: "identificacion",
        sorter: "string",
        vertAlign: "middle",
        headerFilter: "input",
        resizable: false,
    },
    {
        title: "Rol",
        field: "rol",
        sorter: "string",
        vertAlign: "middle",
        headerFilter: "input",
        resizable: false,
        minWidth: 130,
    },
    {
        title: "Correo",
        field: "email",
        sorter: "string",
        vertAlign: "middle",
        headerFilter: "input",
        resizable: false,
        visible: false,
    },
    {
        title: "Celular",
        field: "celular",
        sorter: "string",
        vertAlign: "middle",
        headerFilter: "input",
        resizable: false,
        visible: false,
    },
    {
        title: "Recibe notificaciones",
        field: "puede_recibir_notificaciones",
        vertAlign: "middle",
        resizable: false,
        hozAlign: "center",
        formatter: "tickCross",
        headerFilter: "tickCross",
        visible: false,
        headerFilterParams: { tristate: true },
        headerFilterEmptyCheck: function (value) {
            return value === null
        },
    },
]
